services:
  web:
    build: .
    tty: true
    volumes:
      - .:/apps
    environment:
      - NODE_ENV=development
      - PORT=5174
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 5174:5174
